import type { Metadata } from "next";
import "./globals.css";
import { ButtonPrimary } from "@/components/buttonPrimary/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <h1>No mames que estoy haciendo</h1>
        <ButtonPrimary />
      </body>
    </html>
  );
}
